### ISSUE TITLE
Failed to install / build

### ISSUE THREAD

**Issue by stribor14** [salsergey/QCustomPlot-PyQt#1]
Ubuntu 20.04
sip version 6.5.1

Installing with `pip install QCustomPlot2`, so I tried building it from the source.

When building from the source, `sip-build` fails at linking `cannot find -lqcustomplot`

**Comment by deepgnly** [comment]
+1

**Comment by salsergey** [comment]
I have updated the package. Installing binary wheels with `pip` should work, as well as building from source.
