### ISSUE TITLE
Use different package name for PyQt6

### ISSUE THREAD

**Issue by char101** [salsergey/QCustomPlot-PyQt#4]
Hi,

Since PyQt5 and PyQt6 can be installed separately, it would be better if the bindings for PyQt6 has different name than the bindings for PyQt5 (e.g. QCustomPlot6).

I actually got this problem while testing my PyQt6 build since it has the same name with the PyQt5 bindings from pypi.

**Comment by char101** [comment]
Sorry just found that this is actually the case now. Closing the issue.

**Comment by salsergey** [comment]
OK. I added this feature recently.
