### ISSUE TITLE
please provide binary wheels for python 3.12

### ISSUE THREAD

**Issue by ZeeD** [salsergey/QCustomPlot-PyQt#8]
According to https://pypi.org/project/QCustomPlot-PyQt6/#files the current release of  QCustomPlot-PyQt6 (2.1.1.1) is distributed as source package and in binary packages for (c)python 3.8-->3.11.
could you provide also binary packages for python 3.12?

**Comment by salsergey** [comment]
I've uploaded the wheels. Please test if all works as expected.

**Comment by ZeeD** [comment]
Hi
thanks for the build.
(It may be a problem in my workstation, I'm on a debian trixie/sid ... but)
I managed to install with `pip` without issues, but if I launch a project using the library I get
```
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /home/zed/eclipse-workspace/venv/lib/python3.12/site-packages/QCustomPlot_PyQt6.cpython-312-x86_64-linux-gnu.so)
```

**Comment by ZeeD** [comment]
oh, and also the qt version: it seems your package requires `Qt_6.6`
but I have
```bash
# apt-cache show libqt6core6
Package: libqt6core6
Source: qt6-base
Version: 6.4.2+dfsg-19
[...]
```

**Comment by salsergey** [comment]
So, I've build using Manjaro, and there are newer versions of these libraries. Maybe I can use a virtual machine to build wheels that are more compatible with other distributions.

For now you can try to build it yourself. I guess you need the following packages (or similar): qtbase6-dev, libpython3-dev, pyqt6-dev, python3-pyqt6, python3-pyqtbuild, sip-tools. Then you should be able to execute `sip-build --qmake _path_to_qmake6_` and `sip-install --qmake _path_to_qmake6_`.

**Comment by salsergey** [comment]
Or you can download deb packages here: https://download.opensuse.org/repositories/home:/sergeyopensuse:/gpxviewer/Debian_Testing.

**Comment by salsergey** [comment]
I've built packages in Debian 12 and uploaded to PyPI as version 2.1.1.1.1.1. Please test if it works now.

**Comment by ZeeD** [comment]
Hi.
Sorry for the late reply, and thanks for the build.
The latest version works flawlessly, thanks!
